### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by OndraM** [Symfonisti/symfony.cz#19]
We should have an favicon, and current link is also broken:

```html
<link href="sources/favicon.ico" rel="shortcut icon">
```

Or we may just link to http://symfony.com/favicon.ico...

**Comment by TomasVotruba** [comment]
Good catch!

I agree with one you linked. Could you send PR?

**Comment by Zemistr** [comment]
Favicon is fixed. ;)
#22

**Comment by TomasVotruba** [comment]
Thanks!
