### ISSUE TITLE
Check on mobile

### ISSUE THREAD

**Issue by TomasVotruba** [Symfonisti/symfony.cz#33]
http://design.google.com/resizer/#url=http%3A%2F%2Fsymfony.cz

**Comment by spicimedved** [comment]
What exactly do you want to check? I did quick test with:
- Google Resizer, 
- Chrome developer tool
- phone Sony Z2

It seems to be fine. Do you have some special requirement or idea?

**Comment by TomasVotruba** [comment]
Thank for research. I want to check, what needs to be fixed.
I saw it on somebody's phone and it looked very bad compared to website.

IIRC:

- cities were crashed
- company list too long
- ...

**Comment by TomasVotruba** [comment]
Checked, fine, done :)
